### PR TITLE
modified progress bar component

### PR DESCRIPTION
**Pull request by giteshk11**
Modified progress bar component.

### CODE REVIEW

**Comment by tiagostutz** [comment]
Hi @giteshk11! Thanks for your PR.

Nice work on that, really appreciate the gradient you made. Lovely. 

Before accepting the PR, I have one request that I didn't specified on the issue but it is important: the progress will move as the user makes the choices. So, imagine a scenario in which the user is having 10 steps of choice, the progressbar will start with 0%, then the user makes the first choice and the progress moves to 10%. The users makes the second choice and the progress moves to 20% and so on until 100%. But, there must be the solution must have the flexibility of moving between non-linear progress, like from 0% to 20% or from 50% to 80%. So, I'd like to know what about creating css classes to represent those percentages of progress so we can define the width of progress bar by using this class, like:

- `<div className="progress progress-10">` => 10% progress
- `<div className="progress progress-20">` => 20% progress
- `<div className="progress progress-30">` => 30% progress
...

One last thing... I just added some commit and PR guidelines to the [CONTRIBUTING.md](https://github.com/bancodobrasil/stop-analyzing-embed/blob/master/CONTRIBUTING.md) file. I think it would be good to take a look them as they have some good practices for open source projects and in the next PR we will work following those guidelines.

**Comment by giteshk11** [comment]
@tiagostutz rather than created different classes why don't we just use javascript to make the dynamic?

**Comment by tiagostutz** [comment]
> @tiagostutz rather than creating different classes why don't we just use javascript to make the dynamic?

We will use JS (React) to dynamically add this CSS progress class to the component, but with the behavior itself is visual and is better to rely on CSS. I mean, if we want to just put this progress bar starting at 50%, we just need to add this CSS class. This pattern is used by Bootstrap and other CSS frameworks to decouple visual behaviors and aesthetics from the used context.

I'm building a unit test here to test this behavior and enhancing the ProgressBar component so it will be more clear what I mean. 

I'm pushing it to your branch for you to take a look, is that ok?

**Comment by giteshk11** [comment]
@tiagostutz sure,push it

**Comment by tiagostutz** [comment]
Just pushed it. You can update and take a look please.

**Comment by giteshk11** [comment]
@tiagostutz I saw that you are using bootstrap how about we use utilize the bootstrap attributes and it would look something like this
`<div className={`progress`}>
      <div
        role={`progressbar`}
        className={`progress-bar`}
        aria-valuenow={valueNow}
        aria-valuemin={valueMin}
        aria-valuemax={valueMax}
        style={{ width: valueNow + "%" }}
      ></div>
    </div>`

**Comment by tiagostutz** [comment]
> @tiagostutz I saw that you are using bootstrap how about we use utilize the bootstrap attributes and it would look something like this
> `` <div className={`progress`}> <div role={`progressbar`} className={`progress-bar`} aria-valuenow={valueNow} aria-valuemin={valueMin} aria-valuemax={valueMax} style={{ width: valueNow + "%" }} ></div> </div> ``

Totally, @giteshk11 ! Go ahead.!

The more “bootstrap native” we keep the solution, the better. Thanks for pointing out.

**Comment by giteshk11** [comment]
@tiagostutz I have changed the code and made it bootstrap native. I have added a prop that can change the width of the progress bar. I tested it by changing the width from the dev tools but I don't know how to test it properly. And also we have to modify unit tests as well.

**Comment by tiagostutz** [comment]
I've pulled the code here, made some adjustments and pushed again. I tested in dev tools and adjusted the unity tests as well; take a look and if you think we can enrich the testes, let me know.

I think this PR is good to be merged now. What do you think?

**Comment by giteshk11** [comment]
I've changed the background colour to the gradient to make it look better and I've checked the test cases as well, looks good to me and tests ran successfully, so you can merge this PR 😄.

**Comment by tiagostutz** [comment]
Nice! I loved the gradient... =)

**Pull request merged**
