### PR TITLE
Issue 13: Card component unit test added

### PR DESCRIPTION
**Pull request by bearcub3**
For accessibility, aria-label and role have been included for the card images. While writing unit testing, I thought it would make more sense to have it for images.

At the moment, events has no functionality. So, I didn't write the unit testing for the event. I think we should create an issue regarding this.

### CODE REVIEW

**Comment by tiagostutz** [comment]
Nice, @bearcub3!

I'm resolving the conflict here to accept the PR. Meanwhile, do you want to create this issue for the unit tests of events? I think it is a good idea, Although the [Poppins manifesto](https://github.com/bancodobrasil/poppins/blob/master/MANIFESTO.md) states that we should create only issues that were requested to prevent "issue polution", I think the project is very clean and this issue would be very welcome. Just remember to follow the [Poppins guidelines](https://github.com/bancodobrasil/poppins/blob/master/MANIFESTO.md) and bring it on.!

**Comment by finhaa** [comment]
Hey @tiagostutz!

I don't understand so much how I will resolve this conflicts in a repo from other person. Can you help me on this? Will I need some permissions for commit in that repo?

**Comment by tiagostutz** [comment]
Hi @finhaa !
In the [contribution guidelines](https://github.com/bancodobrasil/stop-analyzing-embed/blob/master/CONTRIBUTING.md#commiting-and-pr-guidelines) you can find a quick cheat on how to checkout the forked repo and update it with the original master contents. 

About the permission stuff, clone the @bearcub3 https://github.com/bearcub3/stop-analyzing-embed.git repo, check `issue-13` branch out, do the merge process to update the codebase (as described above) to bring the "conflict" to be resolved. Resolve the conflict and push the code to the `issue-13` branch. Take a look at the commit history here in the PR and check that I've done some commits in @bearcub3 branch repo.!

**Comment by finhaa** [comment]
Right @tiagostutz !

I'm going to work on this today or at the lastest on this weekend. And thank your for the help!

**Comment by tiagostutz** [comment]
<h4>File size impact</h4>

---

**Error:** Error while trying to generate a snapshot for master.

<pre>TypeError [ERR_INVALID_FILE_URL_HOST]: File URL host must be "localhost" or empty on darwin
    at getPathFromURLPosix (internal/url.js:1330:11)
    at Object.fileURLToPath (internal/url.js:1353:50)
    at urlToFileSystemPath (/Users/tiagostutz/workspace/tiagostutz/stop-analyzing-embed/.github/workflows/file-size-impact/node_modules/@jsenv/file-size-impact/dist/commonjs/main.cjs:930:32)
    at execCommandInProjectDirectory (/Users/tiagostutz/workspace/tiagostutz/stop-analyzing-embed/.github/workflows/file-size-impact/node_modules/@jsenv/file-size-impact/dist/commonjs/main.cjs:3884:14)
    at wrapExternalFunction.catchCancellation (/Users/tiagostutz/workspace/tiagostutz/stop-analyzing-embed/.github/workflows/file-size-impact/node_modules/@jsenv/file-size-impact/dist/commonjs/main.cjs:3891:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async fn (/Users/tiagostutz/workspace/tiagostutz/stop-analyzing-embed/.github/workflows/file-size-impact/node_modules/@jsenv/file-size-impact/dist/commonjs/main.cjs:1182:23)
    at async fn (/Users/tiagostutz/workspace/tiagostutz/stop-analyzing-embed/.github/workflows/file-size-impact/node_modules/@jsenv/file-size-impact/dist/commonjs/main.cjs:1204:23)</pre>

---
<sub>
  Generated by Generated by <a href="https://github.com/jsenv/jsenv-file-size-impact">file size impact</a>
</sub>

**Comment by tiagostutz** [comment]
<h4>File size impact</h4>

---

**Error:** Error while trying to generate a snapshot for master.

<pre>TypeError [ERR_INVALID_FILE_URL_HOST]: File URL host must be "localhost" or empty on darwin
    at getPathFromURLPosix (internal/url.js:1332:11)
    at Object.fileURLToPath (internal/url.js:1355:50)
    at urlToFileSystemPath (/Users/tiagostutz/workspace/tiagostutz/stop-analyzing-embed/.github/workflows/file-size-impact/node_modules/@jsenv/file-size-impact/dist/commonjs/main.cjs:930:32)
    at execCommandInProjectDirectory (/Users/tiagostutz/workspace/tiagostutz/stop-analyzing-embed/.github/workflows/file-size-impact/node_modules/@jsenv/file-size-impact/dist/commonjs/main.cjs:3884:14)
    at wrapExternalFunction.catchCancellation (/Users/tiagostutz/workspace/tiagostutz/stop-analyzing-embed/.github/workflows/file-size-impact/node_modules/@jsenv/file-size-impact/dist/commonjs/main.cjs:3891:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async fn (/Users/tiagostutz/workspace/tiagostutz/stop-analyzing-embed/.github/workflows/file-size-impact/node_modules/@jsenv/file-size-impact/dist/commonjs/main.cjs:1182:23)
    at async fn (/Users/tiagostutz/workspace/tiagostutz/stop-analyzing-embed/.github/workflows/file-size-impact/node_modules/@jsenv/file-size-impact/dist/commonjs/main.cjs:1204:23)</pre>

---
<sub>
  Generated by Generated by <a href="https://github.com/jsenv/jsenv-file-size-impact">file size impact</a>
</sub>

**Pull request merged**
