### PR TITLE
Setup completed for tailwind

### PR DESCRIPTION
**Pull request by giteshk11**
@tiagostutz I've some concerns regarding this pull request

- main.css is a huge file so when I'm pushing the file to the repo it's taking a lot of time (i had to cancel the push operation) to be formatted via prettier, we need to find a way to ignore that file as it is a huge file 
- I have added it to the .gitignore so that it doesn't get pushed on to the repo because it's going to be outputted when we run dev server or build the app.

### CODE REVIEW

**Comment by giteshk11** [comment]
@tiagostutz can you merge the changes if the review is completed?

**Comment by tiagostutz** [comment]
> @tiagostutz can you merge the changes if the review is completed?

Hi @giteshk11 !

Reviewing it right now! =)

**Comment by tiagostutz** [comment]
@giteshk11 just reviewed the PR and this 15MB css file is really a problem we will have to deal with. Not only because of the prettier thing but because of the project building/bundling. I tried to build it here and it took an insane time to finish, althought the final bundle was 1MB length, which is not the best scenario, but acceptable.

I'm doing some research here about how we could address this problem. If you find a way, please comment here. I'll do the same.
🏃🏻‍♂️

**Comment by giteshk11** [comment]
I found this  [https://tailwindcss.com/docs/controlling-file-size/](https://tailwindcss.com/docs/controlling-file-size/) in the official tailwindcss i think i tried to use it but not sure if its working or not

**Comment by giteshk11** [comment]
Found one more [link](https://www.freecodecamp.org/news/how-i-dropped-250kb-of-dead-css-weight-with-purgecss-28821049fb/)

**Comment by tiagostutz** [comment]
> I found this https://tailwindcss.com/docs/controlling-file-size/ in the official tailwindcss i think i tried to use it but not sure if its working or not
> i think we should config prettier in such a way that it should ignore the main.css file as its outputted by build process.

I was reading it and looks like you followed the steps correctly. I checked here the build folder and I was wrong: the CSS is 15MB, 1MB is the file gzipped. So, it looks like the purge thing is not working or something like that. 

I'm doing some more research here

**Comment by tiagostutz** [comment]
Got this! I'm making the changes and commiting to your branch.

Captura de Tela 2020-07-28 às 09 25 31

Reference: https://dev.to/jmhungdev/purging-tailwindcss-without-ejecting-create-react-app-4mef

**Comment by tiagostutz** [comment]
I think we are good to go!

@giteshk11 take a look at changes I've made and if you agree with them we can merge this PR!

**Comment by giteshk11** [comment]
Looks good to me!
You can merge it @tiagostutz

**Pull request merged**
