### PR TITLE
making corrections on the mock-server, package.json added. #58

### PR DESCRIPTION
**Pull request by hannydevelop**
I closed the former pull request and deleted the branch because it was almost impossible making corrections due to the following reasons:
1. i made my former PR from GitHub server without Git bash or Git CMD. yea, the task was a bit easier
2. i tried to do same with this task and after commit, i couldn't change folder for the correction since GitHub deals specifically with files.
3. I cloned the main repository (bancodobrasil/stop-analyzing-embed) and pushed to github (i learnt a lot while doing this, i've only pushed a fresh repository from local to remote)
4. Well, since i am a newbee i had lot of troubles cloning only a branch from the repo, so i thought it wise to delete the branch and create something new!
5.well if you notice closely only, only corrections from the former PR were made. New corrections are welcome, well i feel the git cmd is easier for me as i only need to add and commit.
Thank you so much guys! it was fun doing this task

### CODE REVIEW

**Comment by tiagostutz** [comment]
Hi there @hannydevelop ! I have just pushed some minor fixes to the code and we are good for the merge!
About your message:

> i made my former PR from GitHub server without Git bash or Git CMD. yea, the task was a bit easier
> i tried to do same with this task and after commit, i couldn't change folder for the correction since GitHub deals specifically with files.

OK

>    I cloned the main repository (bancodobrasil/stop-analyzing-embed) and pushed to github (i learnt a lot while doing this, i've only pushed a fresh repository from local to remote)
Perfect.! The main goal here is the learning proccess, so I'm happy to know that.

>    Well, since i am a newbee i had lot of troubles cloning only a branch from the repo, so i thought it wise to delete the branch and create something new!

Nice. What the process I suggest for this branching work is:
1. In your [forked repo page](https://github.com/hannydevelop/stop-analyzing-embed) you click on the branches dropdown and start typing the branch name you want to create, for instance **issue-58**. As this branch doesn't exist, a button to create this issue will be presented, just click on it and it will be created, like this:
Captura de Tela 2020-08-08 às 09 36 17

1. Then, on your bash terminal you clone your repo regularly and then checks out the branch by executing `git checkout <branch_name>`, for instance `git checkout issue-58`.

1. Now you are on the branch and all the `commit` and `push` you do will be on it.

>  5.well if you notice closely only, only corrections from the former PR were made. New corrections are welcome, well i feel the git cmd is easier for me as i only need to add and commit.

Nice!! 🚀  
I have some more functionality to add to mock server so I'll create another issue for that, ok?

**Comment by tiagostutz** [comment]
@eduardomrodrigues I ran locally and the server is working just fine.! 
Please, make a quick review and if you think it is OK to go, please merge this PR.

**Comment by hannydevelop** [comment]
Thanks @tiagostutz for the guide!
Yes, certainly you can open a new issue, I respond immediately!
Well, if you have a react job too I can work on that
Its been nice working with u

**Comment by hannydevelop** [comment]
> @eduardomrodrigues I ran locally and the server is working just fine.!
> Please, make a quick review and if you think it is OK to go, please merge this PR.

Hello @tiagostutz and @eduardomrodrigues haven't heard from you recently!
You can open a new issue if my PR is merged!

**Comment by tiagostutz** [comment]
> > @eduardomrodrigues I ran locally and the server is working just fine.!
> > Please, make a quick review and if you think it is OK to go, please merge this PR.
> 
> Hello @tiagostutz and @eduardomrodrigues haven't heard from you recently!
> You can open a new issue if my PR is merged!

Hi there @hannydevelop !! 
Sorry for being away... I'm on a project deadline until thursday, so I'm 18 hours a day working on it since friday.

You PR is definetaly good to. So I'm merging it now and I'll be back on thursday for sure to open more issues and make some tests!

**Pull request merged**
