### PR TITLE
Changed height to max-height and added object-fit: cover to resolve issue #57

### PR DESCRIPTION
**Pull request by Bob160**
I changed the `height` in the `tsx` files to max-height and added the `object-fit` utility class as used in tailwind.

Thanks for this opportunity and looking forward to doing handling more issues.

### CODE REVIEW

**Comment by tiagostutz** [comment]
Hi @Bob160 !! 
Great PR.! I just reviewed it and for me it is just good to go!
@divyaYK, please take a quick review of this code and if its OK merge thir PR. You know tailwind better than I do. Thanks!
🚀

**Comment by Bob160** [comment]
@divyaYK Kindly have a look at the changes you requested for. Hope this works?

Thanks.

@tiagostutz I'm waiting for my new issue...

**Comment by Bob160** [comment]
> Hey @Bob160!
> Have you looked at the [these tailwind docs](https://tailwindcss.com/docs/object-fit/#app)?
> There's no **class** called `object-fit`, you need to use `object-fit: cover;` **property** and hence `object-cover` class.
> Please make these changes.

@divyaYK I did!

That's true, my bad. Apologies!

Will effect the changes right away.

**Comment by Bob160** [comment]
@divyaYK  The requested changes have been effected. Please, take a look.

Thanks

**Comment by Bob160** [comment]
Thanks @divyaYK 

Wow!!!!!

**Comment by tiagostutz** [comment]
@divyaYK what a great community mantainer you are! 
Thanks a lot for keeping the energy high!
You are the best ❤️ 

I'm on a project deadline here but on thursday I'll be back for sure and we can forward some ideas we have been discussing with @giteshk11

**Pull request merged**
