### PR TITLE
Issue 17

### PR DESCRIPTION
**Pull request by eduardomrodrigues**
@tiagostutz, sorry for this! This is a expensive merge. I install prettier and eslint and configure both.
After that I remove the errors pointed by lint
The majors conflicts are code style issues, I think the prettier in pre commit must solve future problems with this, I can figure out how we put a hook in commit for lint and prettier run.
What do you think?

Sorry again!

### CODE REVIEW

**Comment by tiagostutz** [comment]
Hi @eduardomrodrigues ! Take it easy, there's nothing to sorry about. Those conflicts were expected with this issue... I'm taking a look at the PR now.

About the pre-commit hook, go on: open an issue and let's work on this. Maybe @JapneetSingh5 has some thoughts on that and could help on this issue.?

**Comment by eduardomrodrigues** [comment]
Good ideia! I'm on it! Thank you!

**Comment by tiagostutz** [comment]
@JapneetSingh5 I'm fixing the conflicts now. After doing do, if you could, please make a review. I'll let you know when it is ready to be reviewed.

**Comment by tiagostutz** [comment]
@eduardomrodrigues I added some additional guidelines on https://github.com/bancodobrasil/stop-analyzing-embed/blob/master/CONTRIBUTING.md#commiting-and-pr-guidelines that instructs how to update your branch with the most up to date code from the master. This can be useful in those conflicts forecasted scenarios.

**Comment by JapneetSingh5** [comment]
Hey, great work @eduardomrodrigues, nothing to be sorry about, we are all learning - together. I will review the PR a little bit later in the day today!

**Comment by eduardomrodrigues** [comment]
Thank you, @JapneetSingh5! With your advices I learn a lot of ESLit and Prittier!

**Comment by tiagostutz** [comment]
@JapneetSingh5 just fixed the conflicts. If you could review, that would be great.

**Comment by JapneetSingh5** [comment]
Nice work @eduardomrodrigues @tiagostutz , thankyou for your contributions and giving me the opportunity to be a part of this!

**Pull request merged**
