### PR TITLE
pinterest like cards #30

### PR DESCRIPTION
**Pull request by divyaYK**
Issue #30 

Created Pinterest like cards and made some changes in the colour palette as per the requirement.

### CODE REVIEW

**Comment by tiagostutz** [comment]
Hi there @divyaYK ! 👋🏻  
Thanks for the PR !  Great job on that. 🥰 

I have just two things to point: 

1) the border radius is a bit more rounded, maybe `1rem`.
2) the title and the subtitle of the card should be placed on the bottom of the card. In this imagem below, title is rounded in red and the subtitle in green:

Captura de Tela 2020-07-28 às 20 30 59

**Comment by divyaYK** [comment]
Hi @tiagostutz! ☺️ 

I thought of making those changes but I wasn't sure if I was allowed to.  😅 
Thank you for letting me know. I'll make those changes now.

**Comment by tiagostutz** [comment]
@divyaYK Awsome PR!!  Merging it right now.

I've just invited you to officialy join the team. It would be great if you could accept our invite. 🍰

**Comment by divyaYK** [comment]
@tiagostutz 
Thank you so much for the invite! I'm really happy to collaborate! 😍

**Pull request merged**
